services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: mathgame
      POSTGRES_PASSWORD: mathgame
      POSTGRES_DB: mathgame
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
